services:
  web:
    container_name: careers-app
    build: .
    env_file:
      - .env
    expose:
      - 3000
    volumes:
      - static_volume:/home/ec2-user/careers-webapp/dist

  nginx:
    build: ./nginx
    ports: 
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - /home/ec2-user/.acme.sh/direct-jobs.site_ecc:/home/ec2-user/.acme.sh/direct-jobs.site_ecc
      - static_volume:/home/ec2-user/careers-webapp/dist

volumes:
  static_volume: