services:
  web:
    container_name: careers-app
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000
  nginx:
    build: ./nginx/Dockerfile-dev
    ports: 
      - 80:4567
    depends_on:
      - web