services:
  web:
    container_name: careers-app
    build: .
    env_file:
      - .env
    expose:
      - 3000
  nginx:
    build: ./nginx
    ports: 
      - 80:80
    depends_on:
      - web
    volumes:
      - /home/ec2-user/.acme.sh/direct-jobs.site_ecc:/home/ec2-user/.acme.sh/direct-jobs.site_ecc